export const themes = {
  light: {
    name: "Claro",
    colors: {
      primary: "#2563eb",
      secondary: "#1e40af",
      backgroundColorA: "#dddddd",
      backgroundColorB: "#ffffff",
      accent: "#ff0000",
      text: "#1f2937",
      textMenubar: "#444444",
      textMenubarButton: "#dddddd",
      logoLinkColor: "#191919",
      bgMenubar: "#dddddd",
      bgMenubarButton: "#969696",
      bgMenucontainerColorA: "#818181",
      bgMenucontainerColorB: "#818181",
    },
  },
  dark: {
    name: "Escuro",
    colors: {
      primary: "#3b82f6",
      secondary: "#1e40af",
      backgroundColorA: "#1f2937",
      backgroundColorB: "#1a62c0",
      accent: "#f59e0b",
      text: "#f9fafb",
      textMenubar: "#dddddd",
      textMenubarButton: "#3f3f3f",
      logoLinkColor: "#f9fafb",
      bgMenubar: "#222222",
      bgMenubarButton: "#dddddd",
      bgMenucontainerColorA: "#3f3f3f",
      bgMenucontainerColorB: "#3f3f3f",
    },
  },
};